app_fichesuivie:
    resource: "@AppBundle/Controller/FichesuivieController.php"
    type:     annotation

app_faireparti:
    resource: "@AppBundle/Controller/FairepartiController.php"
    type:     annotation

app_entreprise:
    resource: "@AppBundle/Controller/EntrepriseController.php"
    type:     annotation

app_contenu:
    resource: "@AppBundle/Controller/ContenuController.php"
    type:     annotation

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_competence:
    resource: "@AppBundle/Controller/CompetenceController.php"
    type:     annotation

stage:
    resource: "@StageBundle/Resources/config/routing.yml"
    prefix:   /

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api